=== coffee4breakfast/circleci-python-dockerfile/images.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "pythonConfigureOptions": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 0,
        "uniqueItems": true
      },
      "cflags": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 0,
        "uniqueItems": true
      },
      "systemPackages": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 0,
        "uniqueItems": true
      },
      "configs": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "baseImage": {
              "type": "string"
            },
            "imageTag": {
              "type": "string"
            },
            "pythonVersion": {
              "type": "string",
              "pattern": "^([0-9]+[.])?([0-9]+[.])?([*]|[0-9]+)$"
            },
            "systemPackages": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 0,
              "uniqueItems": true
            },
            "pythonConfigureOptions": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 0,
              "uniqueItems": true
            },
            "cflags": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 0,
              "uniqueItems": true
            }
          },
          "required": ["baseImage", "pythonVersion", "imageTag"]
        },
        "minItems": 1
      }
    },
    "required": ["configs"]
  }

=== coffee4breakfast/circleci-python-dockerfile/images.json
{
    "cflags": [
        "-Os",
        "-pipe",
        "-ftree-vectorize",
        "-fstack-protector-strong",
        "-D_FORTIFY_SOURCE=2",
        "-DNDEBUG"
    ],
    "pythonConfigureOptions": [
        "--enable-shared",
        "--disable-dependency-tracking",
        "--enable-ipv6",
        "--enable-unicode=ucs4",
        "--with-computed-gotos",
        "--with-fpectl"
    ],
    "systemPackages": ["libhdf5-dev"],
    "configs": [
        {
            "baseImage": "circleci/buildpack-deps:xenial",
            "imageTag": "2.7.11-xenial",
            "pythonVersion": "2.7.11"
        },
        {
            "baseImage": "circleci/buildpack-deps:jessie",
            "imageTag": "2.7.11-jessie",
            "pythonVersion": "2.7.11"
        },
        {
            "baseImage": "circleci/buildpack-deps:xenial",
            "imageTag": "2.7.15-xenial",
            "pythonVersion": "2.7.15"
        },
        {
            "baseImage": "circleci/buildpack-deps:jessie",
            "imageTag": "2.7.15-jessie",
            "pythonVersion": "2.7.15"
        },
        {
            "baseImage": "circleci/buildpack-deps:xenial",
            "imageTag": "2.7.11-xenial/psqlclient",
            "pythonVersion": "2.7.11",
            "systemPackages": ["postgresql-client"]
        },
        {
            "baseImage": "circleci/buildpack-deps:jessie",
            "imageTag": "2.7.11-jessie/psqlclient",
            "pythonVersion": "2.7.11",
            "systemPackages": ["postgresql-client"]
        },
        {
            "baseImage": "circleci/buildpack-deps:xenial",
            "imageTag": "2.7.15-xenial/psqlclient",
            "pythonVersion": "2.7.15",
            "systemPackages": ["postgresql-client"]
        },
        {
            "baseImage": "circleci/buildpack-deps:jessie",
            "imageTag": "2.7.15-jessie/psqlclient",
            "pythonVersion": "2.7.15",
            "systemPackages": ["postgresql-client"]
        }
    ]
}
